defaults: 
  - model_defaults # Inherit model_defaults arguments

# --------------------------
#         Model
# --------------------------
model: 'cbm' #  Model's name (to indicate it's a baseline)
tag: 'baseline' # Model's tag for wandb logging
concept_learning: 'hard' # Concept Bottleneck Model baseline, either hard {0,1} or soft logits ['hard', 'soft']

# --------------------------
#         Policy
# --------------------------
inter_policy: 'random,prob_unc' # Comma-separated intervention policies to determine which concept to intervene. Combinable options: ['random','prob_unc']
inter_strategy: 'simple_perc,emp_perc' # Comma-separated intervention strategies to determine how to perform interventions. Automatically set to 'hard' if using hard CBM ['simple_perc', 'emp_perc']
