defaults: 
  - model_defaults # Inherit model_defaults arguments


# --------------------------
#         Model
# --------------------------
model: 'scbm' # Model's name   
tag: 'scbm' # Model's tag for wandb logging
concept_learning: 'hard' # Characteristics of concept bottleneck, either hard {0,1}, or soft logits ['hard', 'soft']. Note that we never explored the soft variant.

# Covariance
cov_type: 'amortized' # Covariance specification. Amortized & global as defined in paper, empirical computes the empirical covariance of the training set and fixes it  ['amortized', 'global', 'empirical']
reg_precision: 'l1' # Regularization strategy of covariance ['l1', None]
reg_weight: 1 # Regularization strength if reg_precision is not None

# --------------------------
#         Policy
# --------------------------
inter_policy: 'random,prob_unc' # Comma-separated intervention policies to determine which concept to intervene. Combinable options: ['random','prob_unc']
inter_strategy: 'simple_perc,emp_perc,conf_interval_optimal' # Comma-separated intervention strategies to determine how to perform interventions. Combinable options: ['simple_perc', 'emp_perc', 'conf_interval_optimal']
level: 0.99 # Confidence level for confidence interval based intervention strategy

