experiment_name: 'experiments' # Name of the experiment
experiment_dir: './experiments/'  # Directory to potentially save the model to

seed: 0 # Random seed
workers: 2 # Number of workers for data loading
save_model: False # Whether to save the model. Set to True for inspecting models post training [True, False]

logging:
  project: 'SCBM' # Name of the wandb project
  mode: 'disabled' # Whether to log to wandb [online, offline, disabled]
  entity: "your_entity" # Your wandb entity